/** Provider Actions **/
export const GOT_PROVIDERS = "GOT_PROVIDERS";
export const CLEAR_PROVIDERS = "CLEAR_PROVIDERS";
export const FILTER_PROVIDERS = "FILTER_PROVIDERS";
export const RESET_FILTERS = "RESET_FILTERS";
export const SEARCHING_FOR_PROVIDERS = "SEARCHING_FOR_PROVIDERS";

/** Bootstrap Actions */
export const BOOTSTRAP_SPECIALTIES = "BOOTSTRAP_SPECIALTIES";
export const BOOTSTRAP_FACILITY_TYPES = "BOOTSTRAP_FACILITY_TYPES";
