export const UPDATE_NAME = 'UPDATE_NAME';

/** Provider Actions **/
export const SEARCH_PROVIDERS = "SEARCH_PROVIDERS";
export const GOT_PROVIDERS = "GOT_PROVIDERS";
export const CLEAR_PROVIDERS = "CLEAR_PROVIDERS";
export const FILTER_DOCTORS = "FILTER_DOCTORS";
export const FILTER_FACILITIES = "FILTER_FACILITIES";
export const RESET_FACILITY_FILTERS = "RESET_FACILITY_FILTERS";

/** Bootstrap Actions */
export const BOOTSTRAP_SPECIALTIES = "BOOTSTRAP_SPECIALTIES";
export const BOOTSTRAP_FACILITY_TYPES = "BOOTSTRAP_FACILITY_TYPES";
